name = "FLOWVPM"
uuid = "6e19019d-7c31-4940-9d16-c3f15dfe6020"
authors = ["Eduardo J. Alvarez <Edo.AlvarezR@gmail.com>"]
version = "2.1.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FLOWExaFMM = "a07d1f4e-0e34-4d8b-bfef-e5b961477d34"

[compat]
julia = "1.4"
FLOWExaFMM = "2.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Cubature = "667455a9-e2ce-5579-9412-b964f529a492"
Elliptic = "b305315f-e792-5b7a-8f41-49f472929428"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"

[targets]
test = ["Test", "Roots", "Cubature", "Elliptic", "LinearAlgebra", "DifferentialEquations"]
